### ISSUE TITLE
Cannot install on Python 3.10 

### ISSUE THREAD

**Issue by alimanfoo** [sanjaynagi/AgamPrimer#29]
Currently AgamPrimer cannot be installed on Python 3.10 or above because of the pinning of the Python dependency. 

This is particularly a problem for colab users because colab has recently been upgraded to Python 3.10.

**Comment by alimanfoo** [comment]
Hi @sanjaynagi, happy to make a PR for this one.

**Comment by sanjaynagi** [comment]
ahhh had not realised this, thank you @alimanfoo !

**Comment by alimanfoo** [comment]
No worries, colab like to surprise us! No upgrade from Python 3.7 for years, then suddenly jump to 3.9 and then on to 3.10 :)

PR #30 should address this.
