### ISSUE TITLE
Declare dependencies in package metadata

### ISSUE THREAD

**Issue by alimanfoo** [sanjaynagi/AgamPrimer#8]
AgamPrimer currently depends on several packages:

```
import pandas as pd 
import allel 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import patches
import malariagen_data
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import gget
import primer3
```

It would be good to express these dependencies in the package metadata so that they get installed automatically when AgamPrimer is installed via pip. 

Not all of these would need to be stated directly, as several will get brought in as transitive dependencies via malariagen_data. However, not all will, e.g., at least seaborn, gget and primer3 would need to be stated explicitly.

There are several different ways to state dependencies. 

If using poetry, these can be declared in the pyproject.toml file, see [an example](https://github.com/malariagen/malariagen-data-python/blob/master/pyproject.toml).

The old-school way to do it is by adding an `install_requires` into setup.py.

**Comment by sanjaynagi** [comment]
Addressed with commits https://github.com/sanjaynagi/AgamPrimer/commit/23cc06037a6398762cfdf1694acfe5df53e89184 and https://github.com/sanjaynagi/AgamPrimer/commit/58dc437d48debc4ec981caeee92b0104fd5f7f5b . From now on working in branches. Thanks Alistair!!
